services:
  pg:
    image: bitnami/postgresql:latest
    container_name: brevly_test
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=brevly_test
    volumes:
      - "./docker:/docker-entrypoint-initdb.d"